### ISSUE TITLE
The Superannuation Dashboard API documentation link is not working

### ISSUE THREAD

**Issue by sudpaul** [apigovau/api-gov-au#14]
Failed to load API definition.
Failed to fetch https://services.ausdx.io/swagger/superannuation-dashboard.yaml

**Comment by colugo** [comment]
Thanks for pointing this out @sudpaul 
I've fixed this up now

**Comment by sudpaul** [comment]
> Thanks for pointing this out @sudpaul
> I've fixed this up now

@colugo Thank you!
