### ISSUE TITLE
Some of the pre existing urls are being redirected to 404

### ISSUE THREAD

**Issue by rahariya** [apigovau/api-gov-au#28]
Previous links were working as mentioned below:

https://api.gov.au/playbook/format.html

https://api.gov.au/playbook/format_needs.html

However, they are now displaying an error as:

404
Page not found :(

The requested page could not be found.

Could you please provide the replaced urls for above 2 endpoints.

**Comment by colugo** [comment]
Hi @rahariya 

I'm the author of the playbook and much of what used to be api.gov.au - but I left many, many years ago.

Unfortunately it now seems long abandoned.

I'm not sure why the links have stopped working, but you can access them through their GitHub pages links at:

- https://playbook.api.gov.au/format.html
- https://playbook.api.gov.au/format_needs.html

Edit: It looks like there's CNAME redirection from https://apigovau.github.io/playbook to https://playbook.api.gov.au

Alastair

**Comment by rahariya** [comment]
Thanks, I will update the urls on our portal.
